### ISSUE TITLE
[Migration] Model relationships

### ISSUE THREAD

**Issue by sanghun89** [sanghun89/giving_profiles#2]
If you visit [http://givingprofiles.org/admin/manage/users?browser=true](http://givingprofiles.org/admin/manage/users?browser=true) You get to see the raw data of everything (without requiring login!)

One good thing about this view is that you get a good idea about the relationship of three main models
`User`, `Donation`, and `Organization`

A/C
- Create migration files to update table indexes
- Reflect the relationship in the model classes
- Organizations table from the old project also have `types`. Implement a good practice to enumerate Organization by its type
- (Optional, Paul can enforce this if he would like to) Migrate the existing "seed" (look `old_giving_profiles/all_org.rb`) to an actual `seed.rb` provided by rails

Estimated Points: 5

**Comment by markdamobi** [comment]
Can you say more about enumerating the organization types? Where are the types defined? From the data, it looks like it just has name and id.

**Comment by uuunk** [comment]
JEeesus that's one hell of a security hole...good thing there's no real data in there.

**Comment by arincon9** [comment]
🤯🤯🤯🤯

**Comment by markdamobi** [comment]
#4
